#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#Start Polybar
$HOME/.config/polybar/launch.sh --forest
#Set Wallpaper
feh --bg-fill ~/Pictures/wallpaper/no_logo.jpg

bspc monitor -d term www steam file

bspc config border_width         2
bspc config window_gap          12
bspc condig bottom_padding	55

#DT configs


bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
#bspc config split_ratio                   0.50
#bspc config borderless_monocle            true
#bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
#bspc config tray-position = right

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a steam desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


